activity_list = {	"1": "Alignment Activity Pre",
				  	"2": "Tall male self paced 400m walk on hard surface w/sneakers",
				  	"3": "Tall female self paced 400m walk on hard surface w/sneakers",
				  	"4": "Tall male self paced 400m run on hard surface w/sneakers",
					"5": "Tall female self paced 400m run on hard surface w/sneakers",
					"6": "Run 1 mile on a flat track under 6 minutes",
					"7": "No disability 0.25 miles Hard surface w/sneaker",
					"8": "SPPB Pos 0.25 miles Hard Surface w/sneaker",
					"9": "Cane 100m Hard Surface w/sneaker",
					"10": "Walker 100m Hard Surface w/sneaker",
					"11": "Treadmill at 27 m*min-1 (1mph) @ 0% grade",
					"12": "Treadmill at 54 m*min-1 (2mph) @ 0% grade",
					"13": "Treadmill at 80 m*min-1 (3mph) @ 0% grade",
					"14": "Treadmill at 80 m*min-1 (3mph) @ 5% grade (as tolerated)",
					"15": "Treadmill at 107 m*min-1 (4mph) @ 0% grade (as tolerated)",
					"16": "Treadmill at 134 m*min-1 (5mph) @ 0% grade (as tolerated)",
					"17": "Treadmill at 170 m*min-1 (6mph) @ 0% grade (as tolerated)",
					"18": "Treadmill at 170 m*min-1 (6mph) @ 5% grade (as tolerated)",
					"19": "Seated, folding/stacking laundry",
					"20": "Standing/Fidgeting with hands while talking",
					"21": "1 minute brushing teth + 1 minute brushing hair",
					"22": "Driving a car",
					"23": "Hard surface walking w/sneakers",
					"24": "Hard surface walking w/sneakers hand in front pocket",
					"25": "Hard surface walking w/sneakers while carry 8 lb. object",
					"26": "Hard surface walking w/sneakers holding cell phone",
					"27": "Hard surface walking w/sneakers holding filled coffee cup",
					"28": "Carpet w High heels or dress shoes",
					"29": "Grass barefoot",
					"30": "Uneven dirt w/sneakers",
					"31": "Up hill 5% grade w high heels or dress shoes",
					"32": "Down hill 5% grade w high heels or dress shoes",
					"33": "Walking up stairs (5 floors)",
					"34": "Walking down stairs (5 floors)",
					"35": "Alignment Activity - Post" }